name: Installer Json Copy Test

on: workflow_dispatch

jobs:
  build:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Build
    uses: ./.github/workflows/build.yml

  installercopytest:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Installer Copy Test
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/

      - name: Upload Installer Json to Leaf
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/libs/leaf-installer.json'
          destination_repo: 'aoqia194/leaf'
          destination_folder: 'loader'
          user_email: '30682549+aoqia194@users.noreply.github.com'
          user_name: 'aoqia194'
