name: Copy Installer Json

on: workflow_dispatch

jobs:
  build:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Build
    uses: ./.github/workflows/build.yml

  copyinstallerjson:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Copy Installer Json
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/

      - name: Get Loader Version
        run: echo "LOADER_VERSION=$(./gradlew -q getLoaderVersion | grep -Eo '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')" >> $GITHUB_ENV

      - name: Upload Installer Json to Leaf
        uses: supsm/copy_file_to_another_repo@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'src/main/resources/leaf-installer.json'
          destination_repo: 'aoqia194/leaf'
          destination_folder: "loader/${{ env.LOADER_VERSION }}.json"
          user_email: '30682549+aoqia194@users.noreply.github.com'
          user_name: 'aoqia194'
