name: Release

on: workflow_dispatch

jobs:
  release:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Release
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #      - name: Fetch Build Output
      #        uses: actions/download-artifact@v4
      #        with:
      #          name: build-output
      #          path: build/

      - name: Build and Release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          BRANCH_NAME: ${{ github.ref }}
        run: ./gradlew build checkVersion publish jreleaserFullRelease -S
