name: Release

on: workflow_dispatch

jobs:
  build:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    if: ${{ github.repository_owner == 'aoqia194' }}
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/

      - name: Release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
        run: ./gradlew checkVersion generateInstallerJson publish |
          jreleaserFullRelease -S -Pleaf.loom.ignoreMissingFiles=true

      # Taken from installerjson.yml

      - name: Get Loader Version
        run: echo "LOADER_VERSION=$(./gradlew -q getLoaderVersion | grep -Eo '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')" >> $GITHUB_ENV

      - name: Upload Installer Json to Leaf
        uses: supsm/copy_file_to_another_repo@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'src/main/resources/leaf-installer.json'
          destination_repo: 'aoqia194/leaf'
          destination_folder: "loader/${{ env.LOADER_VERSION }}.json"
          user_email: '30682549+aoqia194@users.noreply.github.com'
          user_name: 'aoqia194'
